version: '3'
services:
  api:
    image: nominatim:v1
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "7070:8080"
    env_file: 
      - ./.env
    depends_on:
      - db
    entrypoint: sh /app/startapache.sh
  db:
    image: nominatim:v1
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "6432:5432"
    # volumes:
    #   - ./postgres-data:/data
    env_file: 
      - ./.env
    entrypoint: sh /app/startpostgres.sh postgresdata
  init:
    image: nominatim:v1
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: sh /app/init.sh http://download.geofabrik.de/europe/monaco-latest.osm.bz2 postgresdata 4
  update:
    image: nominatim:v1
    build:
      context: ./docker
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - db
    entrypoint: sudo su -u postgres ./src/build/utils/update.php --import-osmosis

